version: '3.7'
services:
  nethermind:
    image: ${NETHERMIND_VERSION}
    init: true
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    volumes:
      - ./data/logs:/nethermind/logs
      - ./data/keystore:/nethermind/keystore
      - ./data/nethermind_db:/nethermind/nethermind_db
    ports:
      - 30303:30303
      - 30303:30303/udp
      - 8545:8545
    environment:
      NETHERMIND_CONFIG: ${CONFIG}
      NETHERMIND_INITCONFIG_ISMINING: "${IS_SIGNING}"
      NETHERMIND_INITCONFIG_WEBSOCKETSENABLED: "true"
      NETHERMIND_KEYSTORECONFIG_PASSWORDFILES: "${KEYSTORE_PASSWORDFILES}"
      NETHERMIND_KEYSTORECONFIG_UNLOCKACCOUNTS: "${VALIDATOR_ADDRESS}"
      NETHERMIND_KEYSTORECONFIG_BLOCKAUTHORACCOUNT: "${BLOCKAUTHOR_ADDRESS}"
      NETHERMIND_JSONRPCCONFIG_ENABLED: "true"
      NETHERMIND_JSONRPCCONFIG_HOST: "0.0.0.0"
      NETHERMIND_MININGCONFIG_TARGETBLOCKGASLIMIT: "${BLOCKGAS_LIMIT}"
      NETHERMIND_METRICSCONFIG_ENABLED: "true"
      NETHERMIND_METRICSCONFIG_INTERVALSECONDS: 30
      NETHERMIND_METRICSCONFIG_NODENAME: "${NODE_NAME}"
      NETHERMIND_METRICSCONFIG_PUSHGATEWAYURL: "${METRICS_URL}"
      NETHERMIND_ETHSTATSCONFIG_ENABLED: "true"
      NETHERMIND_ETHSTATSCONFIG_NAME: "${ETHSTATS_NAME}"
      NETHERMIND_ETHSTATSCONFIG_SECRET: "${ETHSTATS_SECRET}"
      NETHERMIND_ETHSTATSCONFIG_CONTACT: "${ETHSTATS_CONTACT}"
      NETHERMIND_ETHSTATSCONFIG_SERVER: "wss://dai-netstat.poa.network/api"
      NETHERMIND_SEQCONFIG_MINLEVEL: "Info"
      NETHERMIND_SEQCONFIG_SERVERURL: "${SEQ_SERVERURL}"
      NETHERMIND_SEQCONFIG_APIKEY: "${SEQ_APIKEY}"
      NETHERMIND_HEALTHCHECKSCONFIG_ENABLED: "true"
      NETHERMIND_HEALTHCHECKSCONFIG_UIENABLED: "true"
      NETHERMIND_HEALTHCHECKSCONFIG_POLLINGINTERVAL: 10
      NETHERMIND_HEALTHCHECKSCONFIG_SLUG: "/api/health"
      NETHERMIND_AURACONFIG_FORCESEALING: "${AURA_SEALING}"
      NETHERMIND_AURACONFIG_TXPRIORITYCONTRACTADDRESS: ${TXPRIORITYCONTRACTADDRESS}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"