---
- name: Setup nethermind service
  copy:
    src: nethermind.service
    dest: /etc/systemd/system/nethermind.service
    mode: "755"
  notify:
    - reload nethermind
  become: true

- name: Create data directory
  file:
    path: "{{ ansible_env.HOME }}/data"
    state: directory

- name: Copy pullandbuild.sh
  copy:
    src: pullandbuild.sh
    dest: "{{ ansible_env.HOME }}/pullandbuild.sh"
    mode: a+x

- name: Copy restart.sh
  copy:
    src: restart.sh
    dest: "{{ ansible_env.HOME }}/restart.sh"
    mode: a+x
  
- name: Copy shutdown.sh
  copy:
    src: shutdown.sh
    dest: "{{ ansible_env.HOME }}/shutdown.sh"
    mode: a+x

- name: Copy status.sh
  copy:
    src: status.sh
    dest: "{{ ansible_env.HOME }}/status.sh"
    mode: a+x

- name: Copy tail.sh
  copy:
    src: tail.sh
    dest: "{{ ansible_env.HOME }}/tail.sh"
    mode: a+x

- name: Copy up.sh
  copy:
    src: up.sh
    dest: "{{ ansible_env.HOME }}/up.sh"
    mode: a+x

- name: Copy environment file
  copy:
    src: .env
    dest: "{{ ansible_env.HOME }}/data/.env"
  notify:
    - reload nethermind
    - restart nethermind
  changed_when: true
  become: true