---
- name: Setup nethermind service
  copy:
    src: nethermind.service
    dest: /etc/systemd/user/nethermind.service
    mode: "755"
  notify:
    - reload nethermind
  become: true

- name: Create data directory
  file:
    path: "{{ ansible_env.HOME }}/data"
    state: directory

- name: Copy environment file
  copy:
    src: .env
    dest: "{{ ansible_env.HOME }}/data/.env"
  become: true

- name: Register uid {{ ansible_env.USER }}
  command: id -u {{ ansible_env.USER }}
  register: uid

- name: Ensure secrets file will be written to environment file
  lineinfile: 
    dest: "{{ ansible_env.HOME }}/data/.env"
    line: "{{ item }}"
  with_items:
    - "NETHERMIND_ETHSTATSCONFIG_SECRET={{ NETHERMIND_ETHSTATSCONFIG_SECRET }}"
    - "NETHERMIND_ETHSTATSCONFIG_CONTACT={{ NETHERMIND_ETHSTATSCONFIG_CONTACT }}"
    - "NETHERMIND_SEQCONFIG_APIKEY={{ NETHERMIND_SEQCONFIG_APIKEY }}"
    - "NETHERMIND_METRICSCONFIG_PUSHGATEWAYURL={{ NETHERMIND_METRICSCONFIG_PUSHGATEWAYURL }}"
  no_log: True
  notify:
    - reload nethermind
    - restart nethermind
  changed_when: true
  become: true
