---
- name: Clean ethermind environment
  hosts: all
  tasks:
    - name: Clean nethermind environment
      file:
        path: "{{ ansible_env.HOME }}/*"
        state: absent
      become: true
      tags:
        - clean