---
- name: Setup Nethermind Node environment
  hosts: all
  tasks:
    - name: Install dependencies
      include_role:
        name: roles/dependencies
        apply:
          tags: always
      tags:
        - install_dependencies

    - name: Install Nethermind via APT
      include_role:
        name: roles/nethermind-apt
        apply:
          tags: always
      tags:
        - build
