---
- name: Setup Nethermind Node environment
  hosts: all
  tasks:
    - name: Install dependencies
      include_role:
        name: roles/dependencies
        apply:
          tags: always
      tags:
        - install_dependencies

    - name: Build Nethermind from Source
      include_role:
        name: roles/build-nethermind-source
        apply:
          tags: always
      tags:
        - build

