---
- name: Install nodejs
  apt:
    pkg: nodejs
  become: true

- name: Install npm
  apt:
    pkg: npm
  become: true

- name: Cloning the Telemetry service
  git:
    repo: "https://github.com/NethermindEth/nethermind-telemetry.git"
    dest: "{{ ansible_env.HOME }}/nethermind-telemetry"
    force: yes

- name: Setup Telemetry service
  copy:
    src: telemetry.service
    dest: /etc/systemd/system/telemetry.service
    mode: "755"
  notify:
    - reload telemetry
  become: true

- name: Check if FIFO file exists
  stat:
    path: /var/spool/nethermind.sock
  register: fifo_file

- name: Create FIFO file
  command: "mkfifo -m 660 /var/spool/nethermind.sock"
  become: true
  when: fifo_file.stat.exists == False

- name: Change nethermind.sock file permission
  file:
    path: /var/spool/nethermind.sock
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  when: fifo_file.stat.exists == False
  become: true

- name: Install npm modules
  command: chdir={{ ansible_env.HOME }}/nethermind-telemetry npm install
  notify:
    - restart telemetry